#Fill in the blanks
print('Welcome to the DnD MadLib!')
print('Lets create your journey')
fantasy_land = input('What is the name of this land?: ')
character_class = input('What is your character class?: ')
character_name = input('What is the name of your character?: ')
legendary_noun = input('What are we looking for?: ')
weapon = input('What is your weapon of choice?: ')
adjective_1 = input('Enter adjective: ')
animal_companion = input('What is your favorite animal?: ')
adjective_2 = input('Enter adjective: ')
adjective_3 = input('Enter another adjective: ')
noun_1 = input('Enter Noun: ')
creature = input('Enter Mythical Creature: ')
shout= input('YELL SOMETHING!: ')
adjective_4 = input('Enter Adjective: ')
thingamajig = input('Enter a thing that comes to mind: ')
adjective_5 = input('Ente Adjective: ')
food = input('What did you last eat? ')
time_of_day = input('At what time of day is this?: ')
noun_2 = input('Enter noun: ')

#story
print('Once upon a time in the mystical land of', fantasy_land, 'a brave', character_class, 'named', character_name)
print('set out on a quest to find the legendary', legendary_noun, '. Armed with a', weapon, 'and accompanied by their trusty companion')
print(adjective_1, animal_companion, 'they traveled through the', adjective_2, 'forest of', noun_1, '.')
print('Along the way, they encountered a', adjective_3, creature, 'who offered to help them, but only if they could solve its riddle:') 
print('"I am not alive, but I can grow; I don’t have lungs, but I need air. What am I?" After pondering the riddle,', character_name, 'shouted', shout, '!')
print('With the riddle solved, the', creature, 'led them to the hidden cave where the', legendary_noun, 'was said to be kept.') 
print('Inside, they faced', adjective_4, 'traps and', thingamajig, 'but their bravery and cleverness saw them through.') 
print('Finally, they found the', legendary_noun, 'glowing with an', adjective_5, 'light.')
print('Victorious,', character_name, 'returned to', fantasy_land, 'hailed as a hero.') 
print('They celebrated with a feast of', food, 'and danced until the', time_of_day, '.') 
print('And so, the legend of', character_name, 'and the', noun_2, 'was born, inspiring adventurers for generations to come.')
